name: Example CI for Simple Calculator
on:
    push:
        branches: [master]

permissions:
    actions: read          
    security-events: write
    contents: read

jobs:
    ci-gawf-go:
        uses: nandcep/gawf-go/.github/workflows/workflow.yml@master
        secrets: inherit
        with:
            GO_SDK: "1.25.8"
            BINARY_NAME: "simple-calc"
            GOSEC_PARAMS: ""
            SOURCE_TO_IMAGE: false
